variables:
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

trigger:
  - master
  - ci-*
  - refs/tags/v*

pr:
  branches:
    include:
      - master

stages:
  - stage: webpack
    jobs:
      - template: jobs/webpack.yml

  - stage: test
    dependsOn: []
    jobs:
      - template: jobs/test.yml

  - stage: e2e
    dependsOn:
      - webpack
      - test
    jobs:
      - template: jobs/e2e.yml

  - stage: deploy
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn:
      - e2e
    jobs:
      - template: jobs/deploy.yml

  - stage: alsatian
    dependsOn: []
    jobs:
      - template: jobs/alsatian.yml
