jobs:
  - job: alsatian
    displayName: unit tests with alsatian
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: steps/yarn-install.yml

      - bash: yarn run alsatian-test
        displayName: test
