jobs:
  - job: alsatian
    displayName: unit tests with alsatian
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - bash: yarn install
        displayName: install node modules

      - bash: yarn run alsatian-test
        displayName: test
