jobs:
  - job: e2e
    displayName: e2e tests
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - bash: yarn install
        displayName: install node modules

      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: drop
          targetPath: dist

      - bash: yarn run test-e2e
        displayName: test

      - task: PublishTestResults@2
        condition: always()
        inputs:
          testRunner: JUnit
          testResultsFiles: 'junit.xml'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: screenshots
          artifactName: screenshots
