jobs:
  - job: test
    displayName: unit and component tests
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - bash: yarn install
        displayName: install node modules

      - bash: yarn run jest-coverage
        displayName: test

      - task: PublishTestResults@2
        condition: always()
        inputs:
          testRunner: JUnit
          testResultsFiles: 'junit.xml'

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: 'coverage/cobertura-coverage.xml'
