jobs:
  - job: webpack
    displayName: build / production
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - bash: yarn install
        displayName: install node modules

      - bash: yarn run build-release
        displayName: build

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: dist
          artifactName: drop
