jobs:
  - job: webpack
    displayName: build / production
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: steps/yarn-install.yml

      - bash: yarn run build-release
        displayName: build

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: dist
          artifactName: drop
